## @file
# Azure Pipeline build file for a build using ubuntu and GCC5
#
# Copyright (c) Microsoft Corporation.
# Copyright (c) 2020, Hewlett Packard Enterprise Development LP. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
trigger:
- master
- stable/*
pr:
- master
- stable/*

variables:
  GCC5_AARCH64_PREFIX: "/usr/bin/aarch64-linux-gnu-"
  GCC5_ARM_PREFIX:     "/usr/bin/arm-linux-gnueabihf-"
  GCC5_X64_PREFIX:     "/usr/bin/x86_64-linux-gnu-"

jobs:
- template: templates/pr-gate-build-job.yml
  parameters:
    tool_chain_tag: 'GCC5'
    vm_image: 'ubuntu-latest'
    arch_list: "IA32,X64,ARM,AARCH64,RISCV64"

