trigger:
  - master

pr:
  - master

pool:
  vmImage: 'ubuntu-latest'

container: 'quay.io/osteffen/edk2-build:ubuntu-20.04'

workspace:
  clean: all

variables:
  System.Debug: true

steps:
  - bash: apt-get install -y --no-install-recommends qemu-system-x86-64
  - bash: |
      pwd
      ls -laR
  - bash: git submodule update --init

  - bash: ./ci.sh

