## @file
# Azure Pipeline build file for a build using macOS and XCODE5
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
trigger:
- master
- stable/*

pr:
- master
- stable/*

variables:
  - template: templates/defaults.yml

jobs:
- template: templates/pr-gate-build-job.yml
  parameters:
    tool_chain_tag: 'XCODE5'
    vm_image: 'macOS-14'
    arch_list: "IA32,X64"
    usePythonVersion: ''  # use default Python from the vm image
