## @file
# Azure Pipeline build file for a build using Windows and VS2022
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
trigger:
- master
- stable/*

pr:
- master
- stable/*

jobs:
- template: templates/pr-gate-build-job.yml
  parameters:
    tool_chain_tag: 'VS2022'
    vm_image: 'windows-2022'
    arch_list: "IA32,X64"
