name: Code Review

on:
  pull_request:
    branches:
      - sandbox/master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - name: Run a one-line script
      run: echo Hello, world!!!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Run git log
      run: git log --oneline -n30
    - name: Run dir
      run: dir
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: PatchCheck
      run: python BaseTools/Scripts/PatchCheck.py ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
    - name: Send mail
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: [edk2] Create Pull Request
        body: Create pull request on ${{github.repository}}
        to: ${{secrets.GROUPS_IO_EDK2_CODE_REVIEW_EMAIL_ADDRESS}}
        from: TianoCoreGitHubActionsBot
        content_type: text/html
