name: 'Compile UEFI game'
on: 
    push:
        branches:
            - '*'
jobs:
    compile-deez:
        runs-on: ubuntu-latest
        steps:
            - name: Setup build environment
              run: |
               sudo apt update -y
               sudo apt install -y build-essential uuid-dev iasl git nasm python-is-python3
            
            - name: Create bootable ISO
              run: |
                dd if=/dev/zero of=disk.iso bs=1M count=32
                parted --script disk.iso \
                  mklabel gpt \
                  mkpart primary fat32 0% 100% \
                  set 1 esp on \
                  print
                losetup --partscan /dev/loop0 disk.iso
                mkfs.fat -F16 /dev/loop0
                mkdir /mnt/game
                mount /dev/loop0 /mnt/game
                echo "Hello world!" >> /mnt/game/README.md
                umount /mnt/game

            - uses: actions/checkout@v4
              name: Checkout repoistory
              with:
                submodules: recursive

            - name: Compile build tools
              run: | 
                make -C BaseTools
                . edksetup.sh
            
            - name: Compile base tools
              run: |
               make -C BaseTools

            - name: Setup build environment, and build
              run: | 
               export EDK_TOOLS_PATH=${{ github.workspace }}/BaseTools
               . edksetup.sh BaseTools
               build
            
            - name: Save build output
              uses: actions/upload-artifact@v3
              with:
                name: HackingGame EFI
                path: Build/HackingGame/DEBUG_GCC5/**/HackingGame/HackingGame/HackingGame

            - name: Save build output
              uses: actions/upload-artifact@v3
              with:
                name: HackingGame ISO
                path: disk.iso
            
