name: Test arm64 ubuntu-22.04-arm runner hosted by github

on:
  pull_request:

jobs:
  hello_world_job_22:
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
